title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  Your site description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal # or any other theme you're using

# Add this section if it's not already there
navigation:
  - text: "Home"
    url: "/"
  - text: "About Me"
    url: "/about/"
  - text: "Projects"
    url: "/projects/"
  - text: "Published Manuscripts"
    url: "/manuscripts/"
  - text: "Contact"
    url: "/contact/"
